#!/bin/bash

NAME="Telegram Notify"

function tgnotify_interrupt() {
	rm /tmp/telegram-notify > /dev/null 2>&1
}
INTERRUPT_FUNCTIONS+=('tgnotify_interrupt')

function process() {
	if [ ! -f "/usr/local/bin/telegram-notify" ]; then
		return
	fi
	
	#wget -q -O /tmp/telegram-notify "https://github.com/jacklul/scripts/blob/main/telegram-notify/telegram-notify?raw=true"
	REMOTE=`wget -qO- https://github.com/jacklul/scripts/blob/main/telegram-notify/telegram-notify?raw=true`
	
	if [ $? -eq 0 ]; then
		LOCAL=$(cat /usr/local/bin/telegram-notify | sed -n "/Revision history/,/# --/p" | head -n-1 | tail -n+2 | tail -1 | awk '{print $3}')
		LATEST=$(echo $REMOTE | sed -n "/Revision history/,/# --/p" | head -n-1 | tail -n+2 | tail -1 | awk '{print $3}')
		
		if [ "$LATEST" != "" ] && [ "$LOCAL" != "$LATEST" ]; then
			echo "Found Telegram Notify update: $LATEST"
		fi
	fi
}
